// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClcHX90Pbwd_JLH_x_z3VU3Ls8-xUN1Yo',
    appId: '1:201166763483:web:73e93f3e12bbc99341e3fe',
    messagingSenderId: '201166763483',
    projectId: 'fleximart-system',
    authDomain: 'fleximart-system.firebaseapp.com',
    storageBucket: 'fleximart-system.firebasestorage.app',
    measurementId: 'G-G3CFDKWNW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD125VEo6_g0j4H2RMYyZSBQCGwwRbB6qA',
    appId: '1:201166763483:android:d98914bf1dd8eadf41e3fe',
    messagingSenderId: '201166763483',
    projectId: 'fleximart-system',
    storageBucket: 'fleximart-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg2YmdvglebJyJI9Ap-pj7vUlbkeodpas',
    appId: '1:201166763483:ios:a62d5cd34ec6cdec41e3fe',
    messagingSenderId: '201166763483',
    projectId: 'fleximart-system',
    storageBucket: 'fleximart-system.firebasestorage.app',
    iosBundleId: 'com.example.fleximart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg2YmdvglebJyJI9Ap-pj7vUlbkeodpas',
    appId: '1:201166763483:ios:a62d5cd34ec6cdec41e3fe',
    messagingSenderId: '201166763483',
    projectId: 'fleximart-system',
    storageBucket: 'fleximart-system.firebasestorage.app',
    iosBundleId: 'com.example.fleximart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClcHX90Pbwd_JLH_x_z3VU3Ls8-xUN1Yo',
    appId: '1:201166763483:web:4da3b9a8968ea95a41e3fe',
    messagingSenderId: '201166763483',
    projectId: 'fleximart-system',
    authDomain: 'fleximart-system.firebaseapp.com',
    storageBucket: 'fleximart-system.firebasestorage.app',
    measurementId: 'G-JXXE93QWHC',
  );

}